Import('qt_env')

env = qt_env.Clone()

modules = [
    'Core',
    'Gui'
]

if env['QT_MAJOR_VERSION'] > 4:
    modules += [ 'Widgets' ]

env.EnableQt4Modules(['Qt' + n for n in modules],
                     debug = env['CONFIG'] == 'debug')

env.Uic4(env.Glob('*.ui'))

env.AppendUnique(CPPDEFINES = [ 'INSTALLERFOMOD_LIBRARY' ])

env.RequireLibraries('uibase')

# can't use appendunique...
env['CPPPATH'] += [
    '.',
    '${BOOSTPATH}'
]

env.AppendUnique(LIBS = [
    'shell32'
])

lib = env.SharedLibrary('installerFomod', env.Glob('*.cpp'))
env.InstallPlugin(lib)

"""
CONFIG(release, debug|release) {
  QMAKE_CXXFLAGS += /Zi
  QMAKE_LFLAGS += /DEBUG
}
"""
