Import('qt_env')

env = qt_env.Clone()

env.Uic4(env.Glob('*.ui'))

env.AppendUnique(CPPDEFINES = [
    'INSTALLERFOMOD_LIBRARY',
    # boost uses things MS C++ is mldly unhappy about.
    '_SCL_SECURE_NO_WARNINGS'
])

# can't use appendunique...
env['CPPPATH'] += [ '.' ]

env.AppendUnique(CPPPATH = [
    '${BOOSTPATH}'
])

env.AppendUnique(LIBS = [
    'shell32'
])

lib = env.SharedLibrary('installerFomod', env.Glob('*.cpp'))
env.InstallModule(lib)
